spring:
  kafka:
    producer:
      bootstrap-servers: kafka:29092
    consumer:
      bootstrap-servers: kafka:29092
  data:
    cassandra:
      keyspace-name: WikiData
      contact-points: cassandra-46715-0.cloudclusters.net
      port:  18835
      username: wikidata-app
      password: wikidata
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: DC1