server:
  port: 8082
application:
  data:
    batch-size: 2500
    notification-multiplier: 40
    pattern-to-skip: ".*:.*"
    consumer:
      topic: wiki-data
      group-id: wiki-sink
  event:
    group-id: wiki-reader
    topic: event-notification
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      max-block-ms-config: 0
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer