server:
  port: 8082
application:
  data:
    batch-size: 2500
    notification-multiplier: 40
    consumer:
      topic: wiki-data
      group-id: wiki-sink
  event:
    group-id: wiki-reader
    topic: evenet-notification
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      max-block-ms-config: 0
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  data:
    cassandra:
      keyspace-name: WikiData
      contact-points: cassandra-46715-0.cloudclusters.net
      port:  18835
      username: wikidata-app
      password: wikidata
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: DC1