/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ps.wikisink.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventNotification extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8815419994200209360L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventNotification\",\"namespace\":\"com.ps.wikisink.pojo\",\"fields\":[{\"name\":\"fileName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"eventName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"details\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventNotification> ENCODER =
      new BinaryMessageEncoder<EventNotification>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventNotification> DECODER =
      new BinaryMessageDecoder<EventNotification>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventNotification> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventNotification> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventNotification> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventNotification>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventNotification to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventNotification from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventNotification instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventNotification fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String fileName;
   private java.lang.String eventName;
   private java.lang.String details;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventNotification() {}

  /**
   * All-args constructor.
   * @param fileName The new value for fileName
   * @param eventName The new value for eventName
   * @param details The new value for details
   */
  public EventNotification(java.lang.String fileName, java.lang.String eventName, java.lang.String details) {
    this.fileName = fileName;
    this.eventName = eventName;
    this.details = details;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fileName;
    case 1: return eventName;
    case 2: return details;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fileName = value$ != null ? value$.toString() : null; break;
    case 1: eventName = value$ != null ? value$.toString() : null; break;
    case 2: details = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'fileName' field.
   * @return The value of the 'fileName' field.
   */
  public java.lang.String getFileName() {
    return fileName;
  }


  /**
   * Sets the value of the 'fileName' field.
   * @param value the value to set.
   */
  public void setFileName(java.lang.String value) {
    this.fileName = value;
  }

  /**
   * Gets the value of the 'eventName' field.
   * @return The value of the 'eventName' field.
   */
  public java.lang.String getEventName() {
    return eventName;
  }


  /**
   * Sets the value of the 'eventName' field.
   * @param value the value to set.
   */
  public void setEventName(java.lang.String value) {
    this.eventName = value;
  }

  /**
   * Gets the value of the 'details' field.
   * @return The value of the 'details' field.
   */
  public java.lang.String getDetails() {
    return details;
  }


  /**
   * Sets the value of the 'details' field.
   * @param value the value to set.
   */
  public void setDetails(java.lang.String value) {
    this.details = value;
  }

  /**
   * Creates a new EventNotification RecordBuilder.
   * @return A new EventNotification RecordBuilder
   */
  public static com.ps.wikisink.pojo.EventNotification.Builder newBuilder() {
    return new com.ps.wikisink.pojo.EventNotification.Builder();
  }

  /**
   * Creates a new EventNotification RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventNotification RecordBuilder
   */
  public static com.ps.wikisink.pojo.EventNotification.Builder newBuilder(com.ps.wikisink.pojo.EventNotification.Builder other) {
    if (other == null) {
      return new com.ps.wikisink.pojo.EventNotification.Builder();
    } else {
      return new com.ps.wikisink.pojo.EventNotification.Builder(other);
    }
  }

  /**
   * Creates a new EventNotification RecordBuilder by copying an existing EventNotification instance.
   * @param other The existing instance to copy.
   * @return A new EventNotification RecordBuilder
   */
  public static com.ps.wikisink.pojo.EventNotification.Builder newBuilder(com.ps.wikisink.pojo.EventNotification other) {
    if (other == null) {
      return new com.ps.wikisink.pojo.EventNotification.Builder();
    } else {
      return new com.ps.wikisink.pojo.EventNotification.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventNotification instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventNotification>
    implements org.apache.avro.data.RecordBuilder<EventNotification> {

    private java.lang.String fileName;
    private java.lang.String eventName;
    private java.lang.String details;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ps.wikisink.pojo.EventNotification.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fileName)) {
        this.fileName = data().deepCopy(fields()[0].schema(), other.fileName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventName)) {
        this.eventName = data().deepCopy(fields()[1].schema(), other.eventName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.details)) {
        this.details = data().deepCopy(fields()[2].schema(), other.details);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing EventNotification instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ps.wikisink.pojo.EventNotification other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.fileName)) {
        this.fileName = data().deepCopy(fields()[0].schema(), other.fileName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventName)) {
        this.eventName = data().deepCopy(fields()[1].schema(), other.eventName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.details)) {
        this.details = data().deepCopy(fields()[2].schema(), other.details);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'fileName' field.
      * @return The value.
      */
    public java.lang.String getFileName() {
      return fileName;
    }


    /**
      * Sets the value of the 'fileName' field.
      * @param value The value of 'fileName'.
      * @return This builder.
      */
    public com.ps.wikisink.pojo.EventNotification.Builder setFileName(java.lang.String value) {
      validate(fields()[0], value);
      this.fileName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fileName' field has been set.
      * @return True if the 'fileName' field has been set, false otherwise.
      */
    public boolean hasFileName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fileName' field.
      * @return This builder.
      */
    public com.ps.wikisink.pojo.EventNotification.Builder clearFileName() {
      fileName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventName' field.
      * @return The value.
      */
    public java.lang.String getEventName() {
      return eventName;
    }


    /**
      * Sets the value of the 'eventName' field.
      * @param value The value of 'eventName'.
      * @return This builder.
      */
    public com.ps.wikisink.pojo.EventNotification.Builder setEventName(java.lang.String value) {
      validate(fields()[1], value);
      this.eventName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventName' field has been set.
      * @return True if the 'eventName' field has been set, false otherwise.
      */
    public boolean hasEventName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventName' field.
      * @return This builder.
      */
    public com.ps.wikisink.pojo.EventNotification.Builder clearEventName() {
      eventName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'details' field.
      * @return The value.
      */
    public java.lang.String getDetails() {
      return details;
    }


    /**
      * Sets the value of the 'details' field.
      * @param value The value of 'details'.
      * @return This builder.
      */
    public com.ps.wikisink.pojo.EventNotification.Builder setDetails(java.lang.String value) {
      validate(fields()[2], value);
      this.details = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'details' field has been set.
      * @return True if the 'details' field has been set, false otherwise.
      */
    public boolean hasDetails() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'details' field.
      * @return This builder.
      */
    public com.ps.wikisink.pojo.EventNotification.Builder clearDetails() {
      details = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventNotification build() {
      try {
        EventNotification record = new EventNotification();
        record.fileName = fieldSetFlags()[0] ? this.fileName : (java.lang.String) defaultValue(fields()[0]);
        record.eventName = fieldSetFlags()[1] ? this.eventName : (java.lang.String) defaultValue(fields()[1]);
        record.details = fieldSetFlags()[2] ? this.details : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventNotification>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventNotification>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventNotification>
    READER$ = (org.apache.avro.io.DatumReader<EventNotification>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.fileName);

    out.writeString(this.eventName);

    if (this.details == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.details);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.fileName = in.readString();

      this.eventName = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.details = null;
      } else {
        this.details = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.fileName = in.readString();
          break;

        case 1:
          this.eventName = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.details = null;
          } else {
            this.details = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










